#!/bin/bash                                                                                                                      \
                                                                                                                                  
                                                                                                                                 \

arg1=$1
arg2=$2
arg3=$3
for ((i=1;i<=20;i++)); do
    java UnsafeMemory $arg1 $arg2 $arg3 10 5 6 3 0 3 >> tempf
done

grep -oE '[0-9]*\.*[0-9]*' tempf |tr ' ' '\n' >> tempff

awk '{ total += $1 } END { print total/NR }' tempff

rm -f tempf tempff
